export const OBTER_PROJETOS = "OBTER_PROJETOS";
export const ADICIONAR_PROJETO = "ADICIONAR_PROJETO";
export const EDITAR_PROJETO = "EDITAR_PROJETO";
export const REMOVER_PROJETO = "REMOVER_PROJETO";

export const OBTER_TAREFAS = "OBTER_TAREFAS";
export const ADICIONAR_TAREFA = "ADICIONAR_TAREFA";
export const EDITAR_TAREFA = "EDITAR_TAREFA";
export const REMOVER_TAREFA = "REMOVER_TAREFA";
